### ISSUE TITLE
Include atoms in molecules --> then templates --> etc.

### ISSUE THREAD

**Issue by ebiasini** [SC5/sc5-styleguide-tutorial#28]
I've gone through all of the SC5 tutorial and I can now grasp some KSS essentially.
I'm wondering how would it be possible to support a templating system such as https://mustache.github.io/ to feed atoms to molecules for example. Why should I keep copying/pasting markup code?

**Comment by cyberixae** [comment]
Thank you for the feedback. However this is a limitation of the sc5-styleguide tool and not a limitation of the tutorial. Please file a feature request for templating at https://github.com/SC5/sc5-styleguide/issues
